baseurl: https://example.com
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: Call me Sam
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2021
  dateformfull: Mon Jan 2 2021 15:04:05 EST
  description: A new Hugo site.
  favicon: sam.ico
  footerText: Call me Sam, a theme for Hugo.
  homepage: main
  images: tn.png
  mainMenu:
    - link: posts
      text: 博客
    - link: gallery
      text: 杂谈
    # - link: portfolio
    #   text: portfolio
    - link: about
      text: 有关
  title: Call me Sam
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /background.png
        source: /sample_video.mp4
        type: video/mp4
imaging:
  quality: 75
