baseurl: https://shenoybr.github.io/hugo-goa-demo/
builddrafts: no
canonifyurls: no
languageCode: en-US
contentdir: content
layoutdir: layouts
publishdir: public
author: 庄闪闪
title: 庄闪闪的博客
theme: hugo-goa
disqusShortname: https-shenoybr-github-io-hugo-goa-demo
googleAnalytics: XYZ
enableRobotsTXT: yes
params:
  author: 庄闪闪
  authorimage: 
  dateformat: Jan 2, 2021
  description: "在读统计研究生、R爱好者"
  extra:
    copyright: © 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/).
    displayrssicon: no
    highlightjs: yes
    poweredby: yes
    socialmarkup: yes
    toc: yes
  intro: 
  meta:
    description: Simple minimalist theme
    keywords: minimalist,blog,goa,hugo,developer
  social:
    # bitbucket: <username>
    # email: you@example.com
    # facebook: <username>
    # fivehundredpx: <username>
    # flickr: <username>
    # foursquare: <username>
    # github: <username>
    # gitlab: <username>
    # goodreads: <username>
    # google: <username>
    # googlescholar: <account_id>
    # hackernews: <username>
    # instagram: <username>
    # keybase: <username>
    # kickstarter: <username>
    # lastfm: <username>
    # linkedin: <username>
    # patreon: <username>
    # pgp: <key_fingerprint>
    # pintrest: <username>
    # reddit: <username>
    # skype: <username>
    # snapchat: <username>
    # soundcloud: <username>
    # stackoverflow: <username>
    # steam: <username>
    # strava: <username>
    # telegram: <username>
    # tumblr: <username>
    # twitch: <username>
    # twitter: <username>
    # whatsapp: <username>
    # xing: <username>
    # youtube: <channelid>
menu:
  main:
    - identifier: blog
      name: 博客
      url: /blog/
      weight: 100
    - identifier: about
      name: 关于
      url: /about/
      weight: 200
    - identifier: coderag
      name: 杂谈
      url: /coderag/
      weight: 300
